services:
  lmwf_dsn:
    build:
      context: ./docker/lmwf
    command: sleep infinity
    volumes:
      - .:/app
    working_dir: /app
  composer_dsn:
    command: sleep infinity
    image: composer:latest
    working_dir: /app
    volumes:
      - ./vendor:/app/vendor
  phpdoc_dsn:
    image: phpdoc/phpdoc:latest
    working_dir: /data
    volumes:
      - ./src:/data # phpdoc defines a volume at /data, se we can’t select a subfolder