name: 'Set up repository'
runs:
  using: "composite"
  steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '8.4'
        tools: phpcs, phpstan, phpunit

    - run: composer validate --strict
      shell: bash

    - name: Get Composer Cache Directory
      id: composer-cache-directory
      run: |
        echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash

    - name: Cache Composer dependencies
      id: composer-cache
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache-directory.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    - name: Install Composer dependencies
      run: composer install --prefer-dist --no-progress --no-interaction
      shell: bash
