name: Documentation

on:
  workflow_run:
    workflows: [PHPUnit]
    types: [completed]

  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: ./.github/actions/set-up-repository
        with:
          tools: phpdoc

      - name: Install Graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz
      - name: Create "docs" folder if it does not exits
        run: mkdir -p ./docs
      - name: Run deptrac
        continue-on-error: true
        run: vendor/bin/deptrac analyse --formatter=graphviz-image --output docs/diagram.png
      - name: Run phpdoc
        run: |
          cp dev/phpdoc/phpdoc.dist.xml .
          phpdoc
      - uses: actions/download-artifact@v8
        continue-on-error: true
        with:
          artifact-ids: coverage
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage
      - name: Generate JSON file for coverage badge
        if: ${{ steps.download.outcome == 'success' }}
        run: ./dev/phpunit/coverage.php
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './docs'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
