name: PHP CS Fixer

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

env:
  COMPOSER_CACHE_DIRECTORY: vendor

jobs:
  phpunit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: ./.github/actions/set-up-repository

      - name: Check coding style
        run: vendor/bin/php-cs-fixer -n --silent check