name: PHPUnit

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    uses: matthewslouismarie/lm-web-framework/.github/workflows/shared.yml@master
    secrets:
      envPAT: ${{ secrets.envPAT }}

    steps:
    - name: Run test suite
      run: vendor/bin/phpunit tests
