name: PHPStan Level 8

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  phpstan-jn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.5'
      - uses: ./.github/actions/set-up-repository

      - name: Run PHPStan
        run: ./dev/phpstan/phpstan.sh -qn --no-progress