name: PHPUnit

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  phpunit-jn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/set-up-repository

      - name: Run test suite
        run: ./dev/test.sh

      - uses: actions/upload-artifact@v7
        if: ${{ !cancelled() }}
        overwrite: true
        with:
          name: coverage
          path: xml-coverage/index.xml